{% set name = "humaninfinder" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - humanin-finder = humaninfinder.cli:main

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=61.0
  run:
    - python >=3.10
    - click
    - pandas
    - biopython
    - pytorch
    - transformers
    - peptides
    - joblib
    - scikit-learn
    - numpy
    - hmmer >=3.3

test:
  imports:
    - humaninfinder
  commands:
    - humanin-finder --help
    - humanin-finder setup

about:
  home: https://github.com/LaBiOmicS/humanin-finder
  license: MIT
  license_file: LICENSE
  summary: "A professional evolutionary discovery tool for Humanin-like peptides using a Hybrid AI approach."
  dev_url: https://github.com/LaBiOmicS/humanin-finder
